services:
  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=TechUpdate

  mysql:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TechUpdate
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
